package com.hotelapp.core.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

@Entity
@Table(name = "room_history")
public class RoomHistoryEntity {

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    @Column(name = "id", columnDefinition = "bigint")
    private Long id;

    @Column(name = "room_id", columnDefinition = "bigint")
    private Long room_id;

    @Column(name = "from_status", columnDefinition = "varchar(20)")
    private String from_status;

    @Column(name = "to_status", columnDefinition = "varchar(20)")
    private String to_status;

    @Column(name = "notes", columnDefinition = "text")
    private String notes;

    @Column(name = "start_date", columnDefinition = "timestamptz")
    private java.time.OffsetDateTime start_date;

    @Column(name = "end_date", columnDefinition = "timestamptz")
    private java.time.OffsetDateTime end_date;

    @Column(name = "changed_by", columnDefinition = "bigint")
    private Long changed_by;

    @Column(name = "is_auto_generated", columnDefinition = "boolean DEFAULT false")
    private Boolean is_auto_generated;

    @Column(name = "created_at", columnDefinition = "timestamptz DEFAULT CURRENT_TIMESTAMP")
    private java.time.OffsetDateTime created_at;

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public Long getRoomId() { return room_id; }
    public void setRoomId(Long room_id) { this.room_id = room_id; }

    public String getFromStatus() { return from_status; }
    public void setFromStatus(String from_status) { this.from_status = from_status; }

    public String getToStatus() { return to_status; }
    public void setToStatus(String to_status) { this.to_status = to_status; }

    public String getNotes() { return notes; }
    public void setNotes(String notes) { this.notes = notes; }

    public java.time.OffsetDateTime getStartDate() { return start_date; }
    public void setStartDate(java.time.OffsetDateTime start_date) { this.start_date = start_date; }

    public java.time.OffsetDateTime getEndDate() { return end_date; }
    public void setEndDate(java.time.OffsetDateTime end_date) { this.end_date = end_date; }

    public Long getChangedBy() { return changed_by; }
    public void setChangedBy(Long changed_by) { this.changed_by = changed_by; }

    public Boolean isIsAutoGenerated() { return is_auto_generated; }
    public void setIsAutoGenerated(Boolean is_auto_generated) { this.is_auto_generated = is_auto_generated; }

    public java.time.OffsetDateTime getCreatedAt() { return created_at; }
    public void setCreatedAt(java.time.OffsetDateTime created_at) { this.created_at = created_at; }
}
