/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as R403RouteImport } from './routes/403'
import { Route as R423RouteImport } from './routes/423'
import { Route as AdminPortalRouteImport } from './routes/admin-portal'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as CompanyLedgerRouteImport } from './routes/company-ledger'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as ComplimentaryRouteImport } from './routes/complimentary'
import { Route as DataTransferRouteImport } from './routes/data-transfer'
import { Route as EkycRouteImport } from './routes/ekyc'
import { Route as EkycAdminRouteImport } from './routes/ekyc-admin'
import { Route as GuestConfigRouteImport } from './routes/guest-config'
import { Route as GuestPortalRouteImport } from './routes/guest-portal'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as MyRewardsRouteImport } from './routes/my-rewards'
import { Route as NightAuditRouteImport } from './routes/night-audit'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OnlineInventoryRouteImport } from './routes/online-inventory'
import { Route as PaymentApprovalsRouteImport } from './routes/payment-approvals'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as RbacRouteImport } from './routes/rbac'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RoomConfigRouteImport } from './routes/room-config'
import { Route as RoomManagementRouteImport } from './routes/room-management'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as GuestCheckinIndexRouteImport } from './routes/guest-checkin/index'
import { Route as GuestCheckinConfirmRouteImport } from './routes/guest-checkin/confirm'
import { Route as GuestCheckinFormRouteImport } from './routes/guest-checkin/form'
import { Route as GuestCheckinVerifyRouteImport } from './routes/guest-checkin/verify'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalBookRouteImport } from './routes/portal/book'
import { Route as UnsubscribeTokenRouteImport } from './routes/unsubscribe.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R423Route = R423RouteImport.update({
  id: '/423',
  path: '/423',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalRoute = AdminPortalRouteImport.update({
  id: '/admin-portal',
  path: '/admin-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyLedgerRoute = CompanyLedgerRouteImport.update({
  id: '/company-ledger',
  path: '/company-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplimentaryRoute = ComplimentaryRouteImport.update({
  id: '/complimentary',
  path: '/complimentary',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTransferRoute = DataTransferRouteImport.update({
  id: '/data-transfer',
  path: '/data-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const EkycRoute = EkycRouteImport.update({
  id: '/ekyc',
  path: '/ekyc',
  getParentRoute: () => rootRouteImport,
} as any)
const EkycAdminRoute = EkycAdminRouteImport.update({
  id: '/ekyc-admin',
  path: '/ekyc-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestConfigRoute = GuestConfigRouteImport.update({
  id: '/guest-config',
  path: '/guest-config',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestPortalRoute = GuestPortalRouteImport.update({
  id: '/guest-portal',
  path: '/guest-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRewardsRoute = MyRewardsRouteImport.update({
  id: '/my-rewards',
  path: '/my-rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const NightAuditRoute = NightAuditRouteImport.update({
  id: '/night-audit',
  path: '/night-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineInventoryRoute = OnlineInventoryRouteImport.update({
  id: '/online-inventory',
  path: '/online-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentApprovalsRoute = PaymentApprovalsRouteImport.update({
  id: '/payment-approvals',
  path: '/payment-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const RbacRoute = RbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomConfigRoute = RoomConfigRouteImport.update({
  id: '/room-config',
  path: '/room-config',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomManagementRoute = RoomManagementRouteImport.update({
  id: '/room-management',
  path: '/room-management',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestCheckinIndexRoute = GuestCheckinIndexRouteImport.update({
  id: '/guest-checkin/',
  path: '/guest-checkin/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestCheckinConfirmRoute = GuestCheckinConfirmRouteImport.update({
  id: '/guest-checkin/confirm',
  path: '/guest-checkin/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestCheckinFormRoute = GuestCheckinFormRouteImport.update({
  id: '/guest-checkin/form',
  path: '/guest-checkin/form',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestCheckinVerifyRoute = GuestCheckinVerifyRouteImport.update({
  id: '/guest-checkin/verify',
  path: '/guest-checkin/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalBookRoute = PortalBookRouteImport.update({
  id: '/portal/book',
  path: '/portal/book',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeTokenRoute = UnsubscribeTokenRouteImport.update({
  id: '/unsubscribe/$token',
  path: '/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/423': typeof R423Route
  '/admin-portal': typeof AdminPortalRoute
  '/audit-log': typeof AuditLogRoute
  '/bookings': typeof BookingsRoute
  '/communications': typeof CommunicationsRoute
  '/company-ledger': typeof CompanyLedgerRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/complimentary': typeof ComplimentaryRoute
  '/data-transfer': typeof DataTransferRoute
  '/ekyc': typeof EkycRoute
  '/ekyc-admin': typeof EkycAdminRoute
  '/guest-config': typeof GuestConfigRoute
  '/guest-portal': typeof GuestPortalRoute
  '/help': typeof HelpRoute
  '/housekeeping': typeof HousekeepingRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/my-rewards': typeof MyRewardsRoute
  '/night-audit': typeof NightAuditRoute
  '/offers': typeof OffersRoute
  '/online-inventory': typeof OnlineInventoryRoute
  '/payment-approvals': typeof PaymentApprovalsRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/rbac': typeof RbacRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/room-config': typeof RoomConfigRoute
  '/room-management': typeof RoomManagementRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/timeline': typeof TimelineRoute
  '/verify-email': typeof VerifyEmailRoute
  '/guest-checkin/confirm': typeof GuestCheckinConfirmRoute
  '/guest-checkin/form': typeof GuestCheckinFormRoute
  '/guest-checkin/verify': typeof GuestCheckinVerifyRoute
  '/portal/book': typeof PortalBookRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/guest-checkin/': typeof GuestCheckinIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/423': typeof R423Route
  '/admin-portal': typeof AdminPortalRoute
  '/audit-log': typeof AuditLogRoute
  '/bookings': typeof BookingsRoute
  '/communications': typeof CommunicationsRoute
  '/company-ledger': typeof CompanyLedgerRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/complimentary': typeof ComplimentaryRoute
  '/data-transfer': typeof DataTransferRoute
  '/ekyc': typeof EkycRoute
  '/ekyc-admin': typeof EkycAdminRoute
  '/guest-config': typeof GuestConfigRoute
  '/guest-portal': typeof GuestPortalRoute
  '/help': typeof HelpRoute
  '/housekeeping': typeof HousekeepingRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/my-rewards': typeof MyRewardsRoute
  '/night-audit': typeof NightAuditRoute
  '/offers': typeof OffersRoute
  '/online-inventory': typeof OnlineInventoryRoute
  '/payment-approvals': typeof PaymentApprovalsRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/rbac': typeof RbacRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/room-config': typeof RoomConfigRoute
  '/room-management': typeof RoomManagementRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/timeline': typeof TimelineRoute
  '/verify-email': typeof VerifyEmailRoute
  '/guest-checkin/confirm': typeof GuestCheckinConfirmRoute
  '/guest-checkin/form': typeof GuestCheckinFormRoute
  '/guest-checkin/verify': typeof GuestCheckinVerifyRoute
  '/portal/book': typeof PortalBookRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/guest-checkin': typeof GuestCheckinIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/423': typeof R423Route
  '/admin-portal': typeof AdminPortalRoute
  '/audit-log': typeof AuditLogRoute
  '/bookings': typeof BookingsRoute
  '/communications': typeof CommunicationsRoute
  '/company-ledger': typeof CompanyLedgerRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/complimentary': typeof ComplimentaryRoute
  '/data-transfer': typeof DataTransferRoute
  '/ekyc': typeof EkycRoute
  '/ekyc-admin': typeof EkycAdminRoute
  '/guest-config': typeof GuestConfigRoute
  '/guest-portal': typeof GuestPortalRoute
  '/help': typeof HelpRoute
  '/housekeeping': typeof HousekeepingRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/my-rewards': typeof MyRewardsRoute
  '/night-audit': typeof NightAuditRoute
  '/offers': typeof OffersRoute
  '/online-inventory': typeof OnlineInventoryRoute
  '/payment-approvals': typeof PaymentApprovalsRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/rbac': typeof RbacRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/room-config': typeof RoomConfigRoute
  '/room-management': typeof RoomManagementRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/timeline': typeof TimelineRoute
  '/verify-email': typeof VerifyEmailRoute
  '/guest-checkin/confirm': typeof GuestCheckinConfirmRoute
  '/guest-checkin/form': typeof GuestCheckinFormRoute
  '/guest-checkin/verify': typeof GuestCheckinVerifyRoute
  '/portal/book': typeof PortalBookRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/guest-checkin/': typeof GuestCheckinIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/403'
    | '/423'
    | '/admin-portal'
    | '/audit-log'
    | '/bookings'
    | '/communications'
    | '/company-ledger'
    | '/complete-profile'
    | '/complimentary'
    | '/data-transfer'
    | '/ekyc'
    | '/ekyc-admin'
    | '/guest-config'
    | '/guest-portal'
    | '/help'
    | '/housekeeping'
    | '/login'
    | '/loyalty'
    | '/my-rewards'
    | '/night-audit'
    | '/offers'
    | '/online-inventory'
    | '/payment-approvals'
    | '/profile'
    | '/promotions'
    | '/rbac'
    | '/register'
    | '/reports'
    | '/room-config'
    | '/room-management'
    | '/settings'
    | '/support'
    | '/timeline'
    | '/verify-email'
    | '/guest-checkin/confirm'
    | '/guest-checkin/form'
    | '/guest-checkin/verify'
    | '/portal/book'
    | '/unsubscribe/$token'
    | '/guest-checkin/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/403'
    | '/423'
    | '/admin-portal'
    | '/audit-log'
    | '/bookings'
    | '/communications'
    | '/company-ledger'
    | '/complete-profile'
    | '/complimentary'
    | '/data-transfer'
    | '/ekyc'
    | '/ekyc-admin'
    | '/guest-config'
    | '/guest-portal'
    | '/help'
    | '/housekeeping'
    | '/login'
    | '/loyalty'
    | '/my-rewards'
    | '/night-audit'
    | '/offers'
    | '/online-inventory'
    | '/payment-approvals'
    | '/profile'
    | '/promotions'
    | '/rbac'
    | '/register'
    | '/reports'
    | '/room-config'
    | '/room-management'
    | '/settings'
    | '/support'
    | '/timeline'
    | '/verify-email'
    | '/guest-checkin/confirm'
    | '/guest-checkin/form'
    | '/guest-checkin/verify'
    | '/portal/book'
    | '/unsubscribe/$token'
    | '/guest-checkin'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/403'
    | '/423'
    | '/admin-portal'
    | '/audit-log'
    | '/bookings'
    | '/communications'
    | '/company-ledger'
    | '/complete-profile'
    | '/complimentary'
    | '/data-transfer'
    | '/ekyc'
    | '/ekyc-admin'
    | '/guest-config'
    | '/guest-portal'
    | '/help'
    | '/housekeeping'
    | '/login'
    | '/loyalty'
    | '/my-rewards'
    | '/night-audit'
    | '/offers'
    | '/online-inventory'
    | '/payment-approvals'
    | '/profile'
    | '/promotions'
    | '/rbac'
    | '/register'
    | '/reports'
    | '/room-config'
    | '/room-management'
    | '/settings'
    | '/support'
    | '/timeline'
    | '/verify-email'
    | '/guest-checkin/confirm'
    | '/guest-checkin/form'
    | '/guest-checkin/verify'
    | '/portal/book'
    | '/unsubscribe/$token'
    | '/guest-checkin/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R403Route: typeof R403Route
  R423Route: typeof R423Route
  AdminPortalRoute: typeof AdminPortalRoute
  AuditLogRoute: typeof AuditLogRoute
  BookingsRoute: typeof BookingsRoute
  CommunicationsRoute: typeof CommunicationsRoute
  CompanyLedgerRoute: typeof CompanyLedgerRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  ComplimentaryRoute: typeof ComplimentaryRoute
  DataTransferRoute: typeof DataTransferRoute
  EkycRoute: typeof EkycRoute
  EkycAdminRoute: typeof EkycAdminRoute
  GuestConfigRoute: typeof GuestConfigRoute
  GuestPortalRoute: typeof GuestPortalRoute
  HelpRoute: typeof HelpRoute
  HousekeepingRoute: typeof HousekeepingRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MyRewardsRoute: typeof MyRewardsRoute
  NightAuditRoute: typeof NightAuditRoute
  OffersRoute: typeof OffersRoute
  OnlineInventoryRoute: typeof OnlineInventoryRoute
  PaymentApprovalsRoute: typeof PaymentApprovalsRoute
  ProfileRoute: typeof ProfileRoute
  PromotionsRoute: typeof PromotionsRoute
  RbacRoute: typeof RbacRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  RoomConfigRoute: typeof RoomConfigRoute
  RoomManagementRoute: typeof RoomManagementRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TimelineRoute: typeof TimelineRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  GuestCheckinConfirmRoute: typeof GuestCheckinConfirmRoute
  GuestCheckinFormRoute: typeof GuestCheckinFormRoute
  GuestCheckinVerifyRoute: typeof GuestCheckinVerifyRoute
  PortalBookRoute: typeof PortalBookRoute
  UnsubscribeTokenRoute: typeof UnsubscribeTokenRoute
  GuestCheckinIndexRoute: typeof GuestCheckinIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/423': {
      id: '/423'
      path: '/423'
      fullPath: '/423'
      preLoaderRoute: typeof R423RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal': {
      id: '/admin-portal'
      path: '/admin-portal'
      fullPath: '/admin-portal'
      preLoaderRoute: typeof AdminPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-ledger': {
      id: '/company-ledger'
      path: '/company-ledger'
      fullPath: '/company-ledger'
      preLoaderRoute: typeof CompanyLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complimentary': {
      id: '/complimentary'
      path: '/complimentary'
      fullPath: '/complimentary'
      preLoaderRoute: typeof ComplimentaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-transfer': {
      id: '/data-transfer'
      path: '/data-transfer'
      fullPath: '/data-transfer'
      preLoaderRoute: typeof DataTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekyc': {
      id: '/ekyc'
      path: '/ekyc'
      fullPath: '/ekyc'
      preLoaderRoute: typeof EkycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekyc-admin': {
      id: '/ekyc-admin'
      path: '/ekyc-admin'
      fullPath: '/ekyc-admin'
      preLoaderRoute: typeof EkycAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-config': {
      id: '/guest-config'
      path: '/guest-config'
      fullPath: '/guest-config'
      preLoaderRoute: typeof GuestConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-portal': {
      id: '/guest-portal'
      path: '/guest-portal'
      fullPath: '/guest-portal'
      preLoaderRoute: typeof GuestPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-rewards': {
      id: '/my-rewards'
      path: '/my-rewards'
      fullPath: '/my-rewards'
      preLoaderRoute: typeof MyRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/night-audit': {
      id: '/night-audit'
      path: '/night-audit'
      fullPath: '/night-audit'
      preLoaderRoute: typeof NightAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-inventory': {
      id: '/online-inventory'
      path: '/online-inventory'
      fullPath: '/online-inventory'
      preLoaderRoute: typeof OnlineInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-approvals': {
      id: '/payment-approvals'
      path: '/payment-approvals'
      fullPath: '/payment-approvals'
      preLoaderRoute: typeof PaymentApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rbac': {
      id: '/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof RbacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-config': {
      id: '/room-config'
      path: '/room-config'
      fullPath: '/room-config'
      preLoaderRoute: typeof RoomConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-management': {
      id: '/room-management'
      path: '/room-management'
      fullPath: '/room-management'
      preLoaderRoute: typeof RoomManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-checkin/': {
      id: '/guest-checkin/'
      path: '/guest-checkin'
      fullPath: '/guest-checkin/'
      preLoaderRoute: typeof GuestCheckinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-checkin/confirm': {
      id: '/guest-checkin/confirm'
      path: '/guest-checkin/confirm'
      fullPath: '/guest-checkin/confirm'
      preLoaderRoute: typeof GuestCheckinConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-checkin/form': {
      id: '/guest-checkin/form'
      path: '/guest-checkin/form'
      fullPath: '/guest-checkin/form'
      preLoaderRoute: typeof GuestCheckinFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-checkin/verify': {
      id: '/guest-checkin/verify'
      path: '/guest-checkin/verify'
      fullPath: '/guest-checkin/verify'
      preLoaderRoute: typeof GuestCheckinVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/book': {
      id: '/portal/book'
      path: '/portal/book'
      fullPath: '/portal/book'
      preLoaderRoute: typeof PortalBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$token': {
      id: '/unsubscribe/$token'
      path: '/unsubscribe/$token'
      fullPath: '/unsubscribe/$token'
      preLoaderRoute: typeof UnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R403Route: R403Route,
  R423Route: R423Route,
  AdminPortalRoute: AdminPortalRoute,
  AuditLogRoute: AuditLogRoute,
  BookingsRoute: BookingsRoute,
  CommunicationsRoute: CommunicationsRoute,
  CompanyLedgerRoute: CompanyLedgerRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  ComplimentaryRoute: ComplimentaryRoute,
  DataTransferRoute: DataTransferRoute,
  EkycRoute: EkycRoute,
  EkycAdminRoute: EkycAdminRoute,
  GuestConfigRoute: GuestConfigRoute,
  GuestPortalRoute: GuestPortalRoute,
  HelpRoute: HelpRoute,
  HousekeepingRoute: HousekeepingRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  MyRewardsRoute: MyRewardsRoute,
  NightAuditRoute: NightAuditRoute,
  OffersRoute: OffersRoute,
  OnlineInventoryRoute: OnlineInventoryRoute,
  PaymentApprovalsRoute: PaymentApprovalsRoute,
  ProfileRoute: ProfileRoute,
  PromotionsRoute: PromotionsRoute,
  RbacRoute: RbacRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  RoomConfigRoute: RoomConfigRoute,
  RoomManagementRoute: RoomManagementRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TimelineRoute: TimelineRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  GuestCheckinConfirmRoute: GuestCheckinConfirmRoute,
  GuestCheckinFormRoute: GuestCheckinFormRoute,
  GuestCheckinVerifyRoute: GuestCheckinVerifyRoute,
  PortalBookRoute: PortalBookRoute,
  UnsubscribeTokenRoute: UnsubscribeTokenRoute,
  GuestCheckinIndexRoute: GuestCheckinIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
