/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoomManagementRouteImport } from './routes/room-management'
import { Route as RoomConfigRouteImport } from './routes/room-config'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RbacRouteImport } from './routes/rbac'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NightAuditRouteImport } from './routes/night-audit'
import { Route as MyRewardsRouteImport } from './routes/my-rewards'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GuestConfigRouteImport } from './routes/guest-config'
import { Route as EkycAdminRouteImport } from './routes/ekyc-admin'
import { Route as EkycRouteImport } from './routes/ekyc'
import { Route as DataTransferRouteImport } from './routes/data-transfer'
import { Route as ComplimentaryRouteImport } from './routes/complimentary'
import { Route as CompanyLedgerRouteImport } from './routes/company-ledger'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as GuestCheckinIndexRouteImport } from './routes/guest-checkin/index'
import { Route as UnsubscribeTokenRouteImport } from './routes/unsubscribe.$token'
import { Route as GuestCheckinVerifyRouteImport } from './routes/guest-checkin/verify'
import { Route as GuestCheckinFormRouteImport } from './routes/guest-checkin/form'
import { Route as GuestCheckinConfirmRouteImport } from './routes/guest-checkin/confirm'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomManagementRoute = RoomManagementRouteImport.update({
  id: '/room-management',
  path: '/room-management',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomConfigRoute = RoomConfigRouteImport.update({
  id: '/room-config',
  path: '/room-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RbacRoute = RbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NightAuditRoute = NightAuditRouteImport.update({
  id: '/night-audit',
  path: '/night-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRewardsRoute = MyRewardsRouteImport.update({
  id: '/my-rewards',
  path: '/my-rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestConfigRoute = GuestConfigRouteImport.update({
  id: '/guest-config',
  path: '/guest-config',
  getParentRoute: () => rootRouteImport,
} as any)
const EkycAdminRoute = EkycAdminRouteImport.update({
  id: '/ekyc-admin',
  path: '/ekyc-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EkycRoute = EkycRouteImport.update({
  id: '/ekyc',
  path: '/ekyc',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTransferRoute = DataTransferRouteImport.update({
  id: '/data-transfer',
  path: '/data-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplimentaryRoute = ComplimentaryRouteImport.update({
  id: '/complimentary',
  path: '/complimentary',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyLedgerRoute = CompanyLedgerRouteImport.update({
  id: '/company-ledger',
  path: '/company-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestCheckinIndexRoute = GuestCheckinIndexRouteImport.update({
  id: '/guest-checkin/',
  path: '/guest-checkin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeTokenRoute = UnsubscribeTokenRouteImport.update({
  id: '/unsubscribe/$token',
  path: '/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestCheckinVerifyRoute = GuestCheckinVerifyRouteImport.update({
  id: '/guest-checkin/verify',
  path: '/guest-checkin/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestCheckinFormRoute = GuestCheckinFormRouteImport.update({
  id: '/guest-checkin/form',
  path: '/guest-checkin/form',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestCheckinConfirmRoute = GuestCheckinConfirmRouteImport.update({
  id: '/guest-checkin/confirm',
  path: '/guest-checkin/confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/audit-log': typeof AuditLogRoute
  '/bookings': typeof BookingsRoute
  '/communications': typeof CommunicationsRoute
  '/company-ledger': typeof CompanyLedgerRoute
  '/complimentary': typeof ComplimentaryRoute
  '/data-transfer': typeof DataTransferRoute
  '/ekyc': typeof EkycRoute
  '/ekyc-admin': typeof EkycAdminRoute
  '/guest-config': typeof GuestConfigRoute
  '/help': typeof HelpRoute
  '/housekeeping': typeof HousekeepingRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/my-bookings': typeof MyBookingsRoute
  '/my-rewards': typeof MyRewardsRoute
  '/night-audit': typeof NightAuditRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/rbac': typeof RbacRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/room-config': typeof RoomConfigRoute
  '/room-management': typeof RoomManagementRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/timeline': typeof TimelineRoute
  '/verify-email': typeof VerifyEmailRoute
  '/guest-checkin/confirm': typeof GuestCheckinConfirmRoute
  '/guest-checkin/form': typeof GuestCheckinFormRoute
  '/guest-checkin/verify': typeof GuestCheckinVerifyRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/guest-checkin/': typeof GuestCheckinIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/audit-log': typeof AuditLogRoute
  '/bookings': typeof BookingsRoute
  '/communications': typeof CommunicationsRoute
  '/company-ledger': typeof CompanyLedgerRoute
  '/complimentary': typeof ComplimentaryRoute
  '/data-transfer': typeof DataTransferRoute
  '/ekyc': typeof EkycRoute
  '/ekyc-admin': typeof EkycAdminRoute
  '/guest-config': typeof GuestConfigRoute
  '/help': typeof HelpRoute
  '/housekeeping': typeof HousekeepingRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/my-bookings': typeof MyBookingsRoute
  '/my-rewards': typeof MyRewardsRoute
  '/night-audit': typeof NightAuditRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/rbac': typeof RbacRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/room-config': typeof RoomConfigRoute
  '/room-management': typeof RoomManagementRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/timeline': typeof TimelineRoute
  '/verify-email': typeof VerifyEmailRoute
  '/guest-checkin/confirm': typeof GuestCheckinConfirmRoute
  '/guest-checkin/form': typeof GuestCheckinFormRoute
  '/guest-checkin/verify': typeof GuestCheckinVerifyRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/guest-checkin': typeof GuestCheckinIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/audit-log': typeof AuditLogRoute
  '/bookings': typeof BookingsRoute
  '/communications': typeof CommunicationsRoute
  '/company-ledger': typeof CompanyLedgerRoute
  '/complimentary': typeof ComplimentaryRoute
  '/data-transfer': typeof DataTransferRoute
  '/ekyc': typeof EkycRoute
  '/ekyc-admin': typeof EkycAdminRoute
  '/guest-config': typeof GuestConfigRoute
  '/help': typeof HelpRoute
  '/housekeeping': typeof HousekeepingRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/my-bookings': typeof MyBookingsRoute
  '/my-rewards': typeof MyRewardsRoute
  '/night-audit': typeof NightAuditRoute
  '/offers': typeof OffersRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/rbac': typeof RbacRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/room-config': typeof RoomConfigRoute
  '/room-management': typeof RoomManagementRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/timeline': typeof TimelineRoute
  '/verify-email': typeof VerifyEmailRoute
  '/guest-checkin/confirm': typeof GuestCheckinConfirmRoute
  '/guest-checkin/form': typeof GuestCheckinFormRoute
  '/guest-checkin/verify': typeof GuestCheckinVerifyRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/guest-checkin/': typeof GuestCheckinIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/audit-log'
    | '/bookings'
    | '/communications'
    | '/company-ledger'
    | '/complimentary'
    | '/data-transfer'
    | '/ekyc'
    | '/ekyc-admin'
    | '/guest-config'
    | '/help'
    | '/housekeeping'
    | '/login'
    | '/loyalty'
    | '/my-bookings'
    | '/my-rewards'
    | '/night-audit'
    | '/offers'
    | '/profile'
    | '/promotions'
    | '/rbac'
    | '/register'
    | '/reports'
    | '/room-config'
    | '/room-management'
    | '/settings'
    | '/support'
    | '/timeline'
    | '/verify-email'
    | '/guest-checkin/confirm'
    | '/guest-checkin/form'
    | '/guest-checkin/verify'
    | '/unsubscribe/$token'
    | '/guest-checkin/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/audit-log'
    | '/bookings'
    | '/communications'
    | '/company-ledger'
    | '/complimentary'
    | '/data-transfer'
    | '/ekyc'
    | '/ekyc-admin'
    | '/guest-config'
    | '/help'
    | '/housekeeping'
    | '/login'
    | '/loyalty'
    | '/my-bookings'
    | '/my-rewards'
    | '/night-audit'
    | '/offers'
    | '/profile'
    | '/promotions'
    | '/rbac'
    | '/register'
    | '/reports'
    | '/room-config'
    | '/room-management'
    | '/settings'
    | '/support'
    | '/timeline'
    | '/verify-email'
    | '/guest-checkin/confirm'
    | '/guest-checkin/form'
    | '/guest-checkin/verify'
    | '/unsubscribe/$token'
    | '/guest-checkin'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/audit-log'
    | '/bookings'
    | '/communications'
    | '/company-ledger'
    | '/complimentary'
    | '/data-transfer'
    | '/ekyc'
    | '/ekyc-admin'
    | '/guest-config'
    | '/help'
    | '/housekeeping'
    | '/login'
    | '/loyalty'
    | '/my-bookings'
    | '/my-rewards'
    | '/night-audit'
    | '/offers'
    | '/profile'
    | '/promotions'
    | '/rbac'
    | '/register'
    | '/reports'
    | '/room-config'
    | '/room-management'
    | '/settings'
    | '/support'
    | '/timeline'
    | '/verify-email'
    | '/guest-checkin/confirm'
    | '/guest-checkin/form'
    | '/guest-checkin/verify'
    | '/unsubscribe/$token'
    | '/guest-checkin/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuditLogRoute: typeof AuditLogRoute
  BookingsRoute: typeof BookingsRoute
  CommunicationsRoute: typeof CommunicationsRoute
  CompanyLedgerRoute: typeof CompanyLedgerRoute
  ComplimentaryRoute: typeof ComplimentaryRoute
  DataTransferRoute: typeof DataTransferRoute
  EkycRoute: typeof EkycRoute
  EkycAdminRoute: typeof EkycAdminRoute
  GuestConfigRoute: typeof GuestConfigRoute
  HelpRoute: typeof HelpRoute
  HousekeepingRoute: typeof HousekeepingRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MyBookingsRoute: typeof MyBookingsRoute
  MyRewardsRoute: typeof MyRewardsRoute
  NightAuditRoute: typeof NightAuditRoute
  OffersRoute: typeof OffersRoute
  ProfileRoute: typeof ProfileRoute
  PromotionsRoute: typeof PromotionsRoute
  RbacRoute: typeof RbacRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  RoomConfigRoute: typeof RoomConfigRoute
  RoomManagementRoute: typeof RoomManagementRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TimelineRoute: typeof TimelineRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  GuestCheckinConfirmRoute: typeof GuestCheckinConfirmRoute
  GuestCheckinFormRoute: typeof GuestCheckinFormRoute
  GuestCheckinVerifyRoute: typeof GuestCheckinVerifyRoute
  UnsubscribeTokenRoute: typeof UnsubscribeTokenRoute
  GuestCheckinIndexRoute: typeof GuestCheckinIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-management': {
      id: '/room-management'
      path: '/room-management'
      fullPath: '/room-management'
      preLoaderRoute: typeof RoomManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-config': {
      id: '/room-config'
      path: '/room-config'
      fullPath: '/room-config'
      preLoaderRoute: typeof RoomConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rbac': {
      id: '/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof RbacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/night-audit': {
      id: '/night-audit'
      path: '/night-audit'
      fullPath: '/night-audit'
      preLoaderRoute: typeof NightAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-rewards': {
      id: '/my-rewards'
      path: '/my-rewards'
      fullPath: '/my-rewards'
      preLoaderRoute: typeof MyRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-config': {
      id: '/guest-config'
      path: '/guest-config'
      fullPath: '/guest-config'
      preLoaderRoute: typeof GuestConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekyc-admin': {
      id: '/ekyc-admin'
      path: '/ekyc-admin'
      fullPath: '/ekyc-admin'
      preLoaderRoute: typeof EkycAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekyc': {
      id: '/ekyc'
      path: '/ekyc'
      fullPath: '/ekyc'
      preLoaderRoute: typeof EkycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-transfer': {
      id: '/data-transfer'
      path: '/data-transfer'
      fullPath: '/data-transfer'
      preLoaderRoute: typeof DataTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complimentary': {
      id: '/complimentary'
      path: '/complimentary'
      fullPath: '/complimentary'
      preLoaderRoute: typeof ComplimentaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-ledger': {
      id: '/company-ledger'
      path: '/company-ledger'
      fullPath: '/company-ledger'
      preLoaderRoute: typeof CompanyLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-checkin/': {
      id: '/guest-checkin/'
      path: '/guest-checkin'
      fullPath: '/guest-checkin/'
      preLoaderRoute: typeof GuestCheckinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$token': {
      id: '/unsubscribe/$token'
      path: '/unsubscribe/$token'
      fullPath: '/unsubscribe/$token'
      preLoaderRoute: typeof UnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-checkin/verify': {
      id: '/guest-checkin/verify'
      path: '/guest-checkin/verify'
      fullPath: '/guest-checkin/verify'
      preLoaderRoute: typeof GuestCheckinVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-checkin/form': {
      id: '/guest-checkin/form'
      path: '/guest-checkin/form'
      fullPath: '/guest-checkin/form'
      preLoaderRoute: typeof GuestCheckinFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-checkin/confirm': {
      id: '/guest-checkin/confirm'
      path: '/guest-checkin/confirm'
      fullPath: '/guest-checkin/confirm'
      preLoaderRoute: typeof GuestCheckinConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuditLogRoute: AuditLogRoute,
  BookingsRoute: BookingsRoute,
  CommunicationsRoute: CommunicationsRoute,
  CompanyLedgerRoute: CompanyLedgerRoute,
  ComplimentaryRoute: ComplimentaryRoute,
  DataTransferRoute: DataTransferRoute,
  EkycRoute: EkycRoute,
  EkycAdminRoute: EkycAdminRoute,
  GuestConfigRoute: GuestConfigRoute,
  HelpRoute: HelpRoute,
  HousekeepingRoute: HousekeepingRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  MyBookingsRoute: MyBookingsRoute,
  MyRewardsRoute: MyRewardsRoute,
  NightAuditRoute: NightAuditRoute,
  OffersRoute: OffersRoute,
  ProfileRoute: ProfileRoute,
  PromotionsRoute: PromotionsRoute,
  RbacRoute: RbacRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  RoomConfigRoute: RoomConfigRoute,
  RoomManagementRoute: RoomManagementRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TimelineRoute: TimelineRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  GuestCheckinConfirmRoute: GuestCheckinConfirmRoute,
  GuestCheckinFormRoute: GuestCheckinFormRoute,
  GuestCheckinVerifyRoute: GuestCheckinVerifyRoute,
  UnsubscribeTokenRoute: UnsubscribeTokenRoute,
  GuestCheckinIndexRoute: GuestCheckinIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
