#!/usr/bin/env python3
"""Check the Spring route surface against upstream's CI-verified route truth:
<upstream>/docs/api/openapi.json is generated by tests/openapi_drift.rs and
covers every registered route. Reports upstream routes with no Spring mapping
and Spring mappings absent upstream (stale aliases). Exit 1 on any gap with
--strict."""
import glob
import json
import re
import sys

UP = "/Volumes/APPLE EXTERNAL SSD /Personal Projects/hotel-app"
ROOT = "/Volumes/APPLE EXTERNAL SSD /Personal Projects/hotel-app-spring"

# Root-level infra routes legitimately live outside openapi.json's /api tree.
ALLOWED_EXTRA = {("ANY", "/health"), ("GET", "/health"), ("ANY", "/ws/status"),
                 ("GET", "/ws/status")}


def norm(path: str) -> str:
    return re.sub(r"\{[a-zA-Z_]+\}", "{}", path)


def collect_mapped():
    mapped = set()
    for path in glob.glob(ROOT + "/src/main/java/**/*.java", recursive=True):
        src = open(path).read()
        for m in re.finditer(
                r"@(Get|Post|Put|Patch|Delete|RequestMapping)Mapping?\s*\(([^)]*)\)", src):
            ann = m.group(0)
            method = "ANY" if "RequestMapping" in ann.split("(")[0] else \
                m.group(1).upper()
            for pm in re.finditer(r'"([^"]+)"', m.group(2)):
                value = pm.group(1)
                if not value.startswith("/"):
                    continue
                mapped.add((method, norm(value)))
        # Raw WebSocket upgrades are registered via addHandler(handler, "path")
        # in the WebSocketConfigurer, not via @GetMapping. The upgrade request
        # is a GET, so count each registration as one.
        for wm in re.finditer(r'addHandler\s*\([^,]+,\s*"([^"]+)"', src):
            if wm.group(1).startswith("/"):
                mapped.add(("GET", norm(wm.group(1))))
    return mapped


def main():
    spec = json.load(open(UP + "/docs/api/openapi.json"))
    upstream = set()
    for path, ops in spec["paths"].items():
        for method in ops:
            upstream.add((method.upper(), norm(path)))

    mapped = collect_mapped()
    missing = sorted(upstream - mapped)
    extra = sorted(m for m in (mapped - upstream) if m not in ALLOWED_EXTRA
                   and m[1].startswith("/api"))
    print(f"{len(upstream)} upstream; {len(mapped)} spring mapped; "
          f"{len(missing)} missing; {len(extra)} spring-only")
    strict = len(sys.argv) > 1 and sys.argv[1] == "--strict"
    for m, p in missing:
        print("MISSING", m, p)
    for m, p in extra:
        print("EXTRA", m, p)
    if strict and (missing or extra):
        sys.exit(1)


if __name__ == "__main__":
    main()
